name: llmchatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit==1.45.0
    - openai==1.77.0
    - python-dotenv==1.1.0
    - httpx ==0.27.2
    - datetime
    - requests