name: llmchatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit==1.36.0
    - openai==1.12.0
    - python-dotenv==1.0.0
    - httpx ==0.27.2
    - datetime
    - requests